---
title: "Example analysis"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Example analysis}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE,
                      dpi = 150,
                      comment = NA)
library(HIPPO)
library(ggplot2)
library(SingleCellExperiment)
```


## Read the data

```{r}
sce = readRDS("../sce_full_Zhengmix4eq.rds")
ref = data.frame(ensg = rowData(sce)$id,
                 hgnc = rowData(sce)$symbol)
```

## Feature Selection and Hierarchical Clustering

```{r}
set.seed(20191031)
hippo_object = hippo(sce@assays$data$counts, K = 4, z_threshold = 5)
```

## Visualize the selected features at each round

```{r}
hippo_plots = visualize_hippo(hippo_object)
```

```{r, fig.width=3, fig.height=1.5}
hippo_plots$zero_plot
hippo_plots$umap_plot
hippo_plots$tsne_plot
```

## Differential Expression Example

```{r, fig.width=4, fig.height=4}
out = diffexp(hippo_object, top.n = 5, switch_to_hgnc = TRUE, ref = ref)
```
